# Generated by Django 2.2.3 on 2020-04-15 04:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200415_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pubished_date',
            new_name='published_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 4, 35, 49, 849464, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 4, 35, 49, 849464, tzinfo=utc)),
        ),
    ]
